### ISSUE TITLE
wanderlite cube seemingly has missing texture 

### ISSUE THREAD

**Issue by tuxinal** [intergrav/devins-overhaul#11]
![image](https://github.com/intergrav/devins-overhaul/assets/24763016/faa061cb-5a49-46b2-a237-77653b187fcf)

**Comment by blryface** [comment]
I wonder if that's "normal"

**Comment by tuxinal** [comment]
yeah i haven't tested anything outside this modpack

**Comment by tuxinal** [comment]
nope that happens without the modpack too

**Comment by tuxinal** [comment]
i _think_ it's caused by modernfix though

**Comment by tuxinal** [comment]
yeah it's definitely modernfix

**Comment by intergrav** [comment]
if modernfix is causing this, it's probably the dynamic resources mixin
